### ISSUE TITLE
Add edit button to docs pages

### ISSUE THREAD

**Issue by tyssejc** [searchdiscovery/client-kenvue-ga4-dl-spec#19]
Add the following to mkdocs.yml:
```yaml
theme:
  features:
    - content.action.edit
```

Make sure `edit_uri` is set as well.

https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#edit-this-page
